import Script from "next/script";
import "./globals.css";
import { Analytics } from '@vercel/analytics/next';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Script src="/fluid-clean.js"></Script>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
