import Script from "next/script";
import "./globals.css";
import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Anton&display=swap"
          as="style"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"
          crossOrigin="anonymous" />
        <link rel="preload" href="https://fonts.googleapis.com/css2?family=Syne:wght@400..800&display=swap" />

      </head>
      <body>
        <Script src="/fluid-clean.js" strategy="lazyOnload"></Script>
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
