import Script from "next/script";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Script src="/fluid-clean.js"></Script>
        {children}
      </body>
    </html>
  );
}
